# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "spud_events"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dustin DeYoung"]
  s.date = "2012-02-20"
  s.email = "dustin@westlakedesign.com"
  s.files = [
    "app/assets/images/spud/admin/events_thumb.png",
    "app/assets/javascripts/calendar_events.js",
    "app/assets/javascripts/calendars.js",
    "app/assets/javascripts/spud/admin/calendar_events.js",
    "app/assets/javascripts/spud/admin/calendars.js",
    "app/assets/javascripts/spud/admin/events.js",
    "app/assets/javascripts/spud/events.js",
    "app/assets/lib/colorpicker/colorpicker.css",
    "app/assets/lib/colorpicker/colorpicker.js",
    "app/assets/lib/colorpicker/images/blank.gif",
    "app/assets/lib/colorpicker/images/colorpicker_background.png",
    "app/assets/lib/colorpicker/images/colorpicker_hex.png",
    "app/assets/lib/colorpicker/images/colorpicker_hsb_b.png",
    "app/assets/lib/colorpicker/images/colorpicker_hsb_h.png",
    "app/assets/lib/colorpicker/images/colorpicker_hsb_s.png",
    "app/assets/lib/colorpicker/images/colorpicker_indic.gif",
    "app/assets/lib/colorpicker/images/colorpicker_overlay.png",
    "app/assets/lib/colorpicker/images/colorpicker_rgb_b.png",
    "app/assets/lib/colorpicker/images/colorpicker_rgb_g.png",
    "app/assets/lib/colorpicker/images/colorpicker_rgb_r.png",
    "app/assets/lib/colorpicker/images/colorpicker_select.gif",
    "app/assets/lib/colorpicker/images/colorpicker_submit.png",
    "app/assets/lib/colorpicker/images/custom_background.png",
    "app/assets/lib/colorpicker/images/custom_hex.png",
    "app/assets/lib/colorpicker/images/custom_hsb_b.png",
    "app/assets/lib/colorpicker/images/custom_hsb_h.png",
    "app/assets/lib/colorpicker/images/custom_hsb_s.png",
    "app/assets/lib/colorpicker/images/custom_indic.gif",
    "app/assets/lib/colorpicker/images/custom_rgb_b.png",
    "app/assets/lib/colorpicker/images/custom_rgb_g.png",
    "app/assets/lib/colorpicker/images/custom_rgb_r.png",
    "app/assets/lib/colorpicker/images/custom_submit.png",
    "app/assets/lib/colorpicker/images/select.png",
    "app/assets/lib/colorpicker/images/select2.png",
    "app/assets/lib/colorpicker/images/slider.png",
    "app/assets/stylesheets/spud/admin/events.css",
    "app/assets/stylesheets/spud/calendar_events.css",
    "app/assets/stylesheets/spud/calendars.css",
    "app/assets/stylesheets/spud/events.css",
    "app/controllers/calendar_events_controller.rb",
    "app/controllers/calendars_controller.rb",
    "app/controllers/spud/admin/calendar_events_controller.rb",
    "app/controllers/spud/admin/calendars_controller.rb",
    "app/helpers/calendars_helper.rb",
    "app/helpers/spud/admin/calendar_events_helper.rb",
    "app/helpers/spud/admin/calendars_helper.rb",
    "app/models/spud_calendar.rb",
    "app/models/spud_calendar_event.rb",
    "app/views/calendar_events/show.html.erb",
    "app/views/calendars/_calendar.html.erb",
    "app/views/calendars/_calendar_options.html.erb",
    "app/views/calendars/show.html.erb",
    "app/views/layouts/spud/admin/events/detail.html.erb",
    "app/views/spud/admin/calendar_events/_calendar.html.erb",
    "app/views/spud/admin/calendar_events/_form.html.erb",
    "app/views/spud/admin/calendar_events/edit.html.erb",
    "app/views/spud/admin/calendar_events/index.html.erb",
    "app/views/spud/admin/calendar_events/new.html.erb",
    "app/views/spud/admin/calendars/_calendar_legend.html.erb",
    "app/views/spud/admin/calendars/_form.html.erb",
    "app/views/spud/admin/calendars/edit.html.erb",
    "app/views/spud/admin/calendars/new.html.erb",
    "config/application.rb",
    "config/boot.rb",
    "config/routes.rb",
    "lib/spud_events.rb",
    "lib/spud_events/calendar_builder.rb",
    "lib/spud_events/configuration.rb",
    "lib/spud_events/engine.rb",
    "lib/spud_events/table_builder.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Spud Events Engine"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

