# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "spud_events"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.date = "2012-02-16"
  s.files = [
    "app/assets/images/admin/events_thumb.png",
    "app/assets/javascripts/calendar_events.js",
    "app/assets/javascripts/calendars.js",
    "app/assets/javascripts/spud/admin/calendar_events.js",
    "app/assets/javascripts/spud/admin/calendars.js",
    "app/assets/stylesheets/calendar_events.css",
    "app/assets/stylesheets/calendars.css",
    "app/assets/stylesheets/spud/admin/calendar_events.css",
    "app/assets/stylesheets/spud/admin/calendars.css",
    "app/controllers/calendar_events_controller.rb",
    "app/controllers/calendars_controller.rb",
    "app/controllers/spud/admin/calendar_events_controller.rb",
    "app/controllers/spud/admin/calendars_controller.rb",
    "app/helpers/calendar_events_helper.rb",
    "app/helpers/calendars_helper.rb",
    "app/helpers/spud/admin/calendar_events_helper.rb",
    "app/helpers/spud/admin/calendars_helper.rb",
    "app/models/spud_calendar.rb",
    "app/models/spud_calendar_event.rb",
    "config/application.rb",
    "config/boot.rb",
    "config/routes.rb",
    "lib/spud_events.rb",
    "lib/spud_events/configuration.rb",
    "lib/spud_events/engine.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Spud Events Engine"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

